name: Install metagen-js
runs:
  using: composite
  steps:
  - name: Install
    shell: bash
    run: |-
      npm install -g https://github.com/kagekirin/metagen-js/tarball/main
  - name: Verify installation
    shell: bash
    run: |-
      which metagen
      metagen --version
